Implementando Feature: EmptyView
devpass-tech/challenge-onboarding pull request #26
Opened 2021-11-10 22:03 UTC by luizamq

Criada uma página EmptyView.swift com uma classe EmptyView

2021-11-11 20:47 UTC, rdgborges commented on solutions/devsprint-5/OnboardingChallenge/Screens/List/EmptyView.swift
> +        stackView.translatesAutoresizingMaskIntoConstraints = false
Para utilizar essa stack view para adicionar os labels, vc precisa configurá-la para ser vertical:

`stackView.axis = .vertical`

2021-11-11 20:47 UTC, rdgborges commented on solutions/devsprint-5/OnboardingChallenge/Screens/List/EmptyView.swift
> +        self.backgroundColor = .none
Pode usar `backgroundColor = .white`

2021-11-11 20:47 UTC, rdgborges commented on solutions/devsprint-5/OnboardingChallenge/Screens/List/EmptyView.swift
> +        self.addSubview(self.emptyTitleLabel)
Uma vez definida a stack view lá acima, aqui você substitui essas linhas por:

```
self.addSubview(stackView)
self.stackView.addArrangedSubview(self.emptyTitleLabel)
self.stackView.addArrangedSubview(self.emptySubtitleLabel)
```

2021-11-11 20:47 UTC, rdgborges commented on solutions/devsprint-5/OnboardingChallenge/Screens/List/EmptyView.swift
> +            self.emptyTitleLabel.centerXAnchor.constraint(equalTo: self.centerXAnchor).isActive = true
Unicas constraints necessárias utilizando stack view:

```
self.stackView.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
self.stackView.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
self.stackView.topAnchor.constraint(equalTo: topAnchor).isActive = true
self.stackView.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
```

2021-11-15 20:22 UTC, luizamq commented on solutions/devsprint-5/OnboardingChallenge/Screens/List/EmptyView.swift
> +        stackView.translatesAutoresizingMaskIntoConstraints = false
Feito

2021-11-15 20:22 UTC, luizamq commented on solutions/devsprint-5/OnboardingChallenge/Screens/List/EmptyView.swift
> +        self.backgroundColor = .none
Feito

2021-11-15 20:22 UTC, luizamq commented on solutions/devsprint-5/OnboardingChallenge/Screens/List/EmptyView.swift
> +        self.addSubview(self.emptyTitleLabel)
Feito

2021-11-18 00:26 UTC, rdgborges requested changes
PARABÉNS PELO SEU PRIMEIRO PR, LUIZA! 🥳🥳🥳

Está tudo certo com o componente. Basta remover um código temporário que escreveu na ListViewController.

2021-11-18 00:26 UTC, rdgborges commented on solutions/devsprint-5/OnboardingChallenge/Screens/List/ListViewController.swift
> +    private var emptyView: UIView {
Pode remover esse código por que não precisaremos dele.

2021-11-18 00:26 UTC, rdgborges commented on solutions/devsprint-5/OnboardingChallenge/Screens/List/ListViewController.swift
> +        _ = EmptyViewConfiguration(title: "No repositories found" , subtitle: "Search for users to see their public repositories here!")
Remover esse código.

2021-11-18 00:26 UTC, rdgborges commented on solutions/devsprint-5/OnboardingChallenge/Screens/List/ListViewController.swift
> +        self.view = self.emptyView
Alterar para `self.view = self.listView`

2021-11-18 13:01 UTC, rdgborges approved these changes

2021-11-18 13:02 UTC, merged